version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/media_tool"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/media_tool/example"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/media_tool_platform_interface"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/media_tool_darwin"
    schedule:
      interval: "daily"