name: media_tool_macos
description: MacOS implementation of the media_tool plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

flutter:
  plugin:
    implements: media_tool
    platforms:
      macos:
        pluginClass: MediaToolPlugin
        dartPluginClass: MediaToolMacOS

dependencies:
  flutter:
    sdk: flutter
  media_tool_platform_interface:
    path: ../media_tool_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0
