name: media_tool
description: Crossplatform video, image and audio processing via native platform code.
homepage: https://github.com/starkdmi/media_tool_flutter
repository: https://github.com/starkdmi/media_tool_flutter
version: 0.1.0

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=1.20.0"

flutter:
  plugin:
    platforms:
      ios:
        default_package: media_tool_darwin
      macos:
        default_package: media_tool_darwin
      android:
        package: media_tool_ffmpeg
        default_package: media_tool_ffmpeg
        pluginClass: MediaToolFFmpeg

dependencies:
  flutter:
    sdk: flutter
  media_tool_darwin: ">=0.1.0 <1.0.0"
  media_tool_ffmpeg: ">=0.1.0 <1.0.0"
  media_tool_platform_interface: ">=0.1.0 <1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  # mocktail: ">=0.3.0 <2.0.0"
  plugin_platform_interface: ">=2.0.0 <3.0.0"
  very_good_analysis: ">=2.0.0 <6.0.0"
