name: media_tool_platform_interface
description: A common platform interface for the media_tool_flutter plugin.
homepage: https://github.com/starkdmi/media_tool_flutter
repository: https://github.com/starkdmi/media_tool_flutter/tree/main/media_tool_platform_interface
version: 0.1.3

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ">=2.0.0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ">=5.0.0 <6.0.0"
