disabled_rules:
  - cyclomatic_complexity
  - function_body_length

included: 
  - Classes
 
force_cast: warning

line_length: 256

type_body_length:
  warning: 500 
  error: 800

file_length:
  warning: 1000
  error: 1250