name: media_tool_example
description: Demonstrates how to use the media_tool plugin.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  media_tool:
    # When depending on this package from a real application you should use:
    #   media_tool: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

  file_picker: ^5.3.2
  path_provider: ^2.0.15
  uuid: ^3.0.7

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
