name: media_tool_example
description: Demonstrates how to use the media_tool plugin.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  media_tool:
    # When depending on this package from a real application you should use:
    #   media_tool: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  media_tool_platform_interface:
    path: ../../media_tool_platform_interface/

  file_picker: ">=5.5.0 <7.0.0"
  path_provider: ">=2.1.1 <3.0.0"
  uuid: ">=4.0.0 <5.0.0"

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ">=5.0.0 <6.0.0"

flutter:
  uses-material-design: true
