name: media_tool_android

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/media_tool_android.yaml"
      - "media_tool_android/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/media_tool_android.yaml"
      - "media_tool_android/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.3.10
      working_directory: media_tool_android

