name: media_tool_darwin
description: Darwin (iOS, macOS) implementation of the media_tool_flutter plugin. The MediaToolSwift library is used.
homepage: https://github.com/starkdmi/media_tool_flutter
repository: https://github.com/starkdmi/media_tool_flutter/tree/main/media_tool_darwin
version: 0.1.0

environment:
  sdk: ">=2.18.0 <4.0.0"
  # Flutter versions prior to 3.7 did not support the sharedDarwinSource option.
  flutter: ">=3.7.0"

flutter:
  plugin:
    implements: media_tool_flutter
    platforms:
      ios:
        pluginClass: MediaToolPlugin
        dartPluginClass: MediaToolDarwin
        sharedDarwinSource: true
      macos:
        pluginClass: MediaToolPlugin
        dartPluginClass: MediaToolDarwin
        sharedDarwinSource: true

dependencies:
  flutter:
    sdk: flutter
  media_tool_platform_interface: ">=0.1.0 <1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ">=2.0.0 <3.0.0"
  very_good_analysis: ">=5.0.0 <6.0.0"
